dist: trusty
sudo: required
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install`
install: echo "skip bundle install"

services: docker

# Ensure we make ChefDK's Ruby the default
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script:
  - cookstyle
  - foodcritic .
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml chef exec kitchen verify
